### ISSUE TITLE
kotlin.TypeCastException: null cannot be cast to non-null type 

### ISSUE THREAD

**Issue by johnWorrell** [satamas/fortran-plugin#35] opened 2018-09-09 18:19 UTC
Not sure what is causing this:

kotlin.TypeCastException: null cannot be cast to non-null type org.jetbrains.fortran.lang.psi.ext.FortranNamedElement
	at org.jetbrains.fortran.lang.psi.mixin.FortranBlockDataImplMixin.getUnit(FortranBlockDataImplMixin.kt:27)
	at org.jetbrains.fortran.lang.resolve.FortranPathReferenceImpl.resolveInProjectFiles(FortranPathReferenceImpl.kt:219)
	at org.jetbrains.fortran.lang.resolve.FortranPathReferenceImpl.resolveName(FortranPathReferenceImpl.kt:164)
	at org.jetbrains.fortran.lang.resolve.FortranPathReferenceImpl.resolveWithoutFiltering(FortranPathReferenceImpl.kt:59)
	at org.jetbrains.fortran.lang.resolve.FortranPathReferenceImpl.resolveInner(FortranPathReferenceImpl.kt:23)
	at org.jetbrains.fortran.lang.resolve.FortranReferenceBase$multiResolve$1.resolve(FortranReferenceBase.kt:24)
	at org.jetbrains.fortran.lang.resolve.FortranReferenceBase$multiResolve$1.resolve(FortranReferenceBase.kt:13)
	at org.jetbrains.fortran.lang.resolve.FortranReferenceBase$multiResolve$1.resolve(FortranReferenceBase.kt:23)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:150)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:99)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:149)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:180)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:172)
	at org.jetbrains.fortran.lang.resolve.FortranReferenceBase.multiResolve(FortranReferenceBase.kt:23)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:47)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:382)
	at com.intellij.codeInsight.TargetElementUtil.b(TargetElementUtil.java:359)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:231)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:203)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:81)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.e(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by satamas** [comment] 2018-10-13 14:14
Thanks for report and sorry for not responding for a long time. I've fixed the issue.
Duplicate of #34

**Closed** 2018-10-13 14:14 UTC
Labels: duplicate
